pi-top/pi-top-Python-SDK

README.rst
=> Use shields.io for badges

.github/workflows/build.yml, debian/changelog
=> Patch changelog in Debian Docker container

debian/changelog, debian/control, docs/getting_started.rst
=> Fix package names

pitop/battery/battery.py, pitop/display/display.py, pitop/miniscreen/buttons/buttons.py, pitop/miniscreen/oled/oled.py
=> Add ptdm subscribe event functionality

debian/changelog, pitop/miniscreen/oled/core/device_controller.py, pitop/miniscreen/oled/oled.py
Fix recursion issue when resetting OLED
=> Fix OLED resetting

pitop/miniscreen/buttons/buttons.py, pitopcli/oled.py, pitopcli/pitop.py
* Improve miniscreen button importing to speed miniscreen imports
* Handle Ctrl+C in OLED CLI
* CLI main function returns exit code for entry point script
=> Improve CLI handling

pitop/system/pitop.py
Bug reported by many users on forum, unable to do Further lessons because of this
=> Fix bug in get_component - return statement had vanished

.github/workflows/deploy-published-release.yml, .github/workflows/draft-release-from-tag.yml, .github/workflows/publish-release.yml
=> Add release publishing GitHub Actions workflow

pitop/webserver/run.py
I saw discussion on the webserver pr #256 that the video was not working well. This is at least partly due to the generator function sending the frames running a non-blocked loop sending as often as possible, not just once for each frame. Sending frames repeatedly will waste time and resources that can be used delivery each frame promptly. I tested this briefly and it seems to have made the latency pretty low and consistent (when opening the webpage on my PC over wifi - VNC introduces quite a bit of latency)
=> Ensure webserver video endpoint sends each frame only once

.github/workflows/test-and-build-on-all-commits.yml
=> OS-969 Add pre-commit checks to CI

debian/py3dist-overrides, docs/conf.py, pitop/pulse/configuration.py, setup.py
=> Pulse: replace SMBus dep with common lib

pitop/protoplus/adc.py
=> Proto+: use public I2C methods

.github/workflows/test-and-build-on-all-commits.yml, README.rst, setup.py
Closes #2
Also removes workflow job to run flake8 as this is already handled by pre-commit
Also drops unnecessary `fetch-depth: 0`
=> Test coverage reporting

pitop/pma/servo_controller.py, pitop/pma/servo_motor.py, tests/test_pma_servo_controller.py
=> Add smooth acceleration mode to servos

pitop/pma/imu.py, pitop/pma/imu_controller.py, pitopcli/imu_calibration.py
=> Remove IMU property-setting recursion

examples/camera/camera_image_processing_stream_opencv.py, examples/pulse/leds-cpu_temp.py, examples/pulse/leds-cpu_usage.py, examples/system/miniscreen/miniscreen_display_particles.py, pitop/camera/camera.py, pitop/core/mixins/recreatable.py, pitop/keyboard/keyboard_button.py, pitop/labs/webserver/__init__.py, pitop/miniscreen/buttons/buttons.py, pitop/pma/components.py, pitop/pma/ultrasonic_sensor.py, pitop/robotics/configurations.py, pitopcli/deprecated_cli_runner.py, pitopcli/imu_calibration.py, pitopcli/oled.py, pitopcli/pitop.py, setup.py
Mostly syntax fixes.
Moved legacy PMA import method `pma/components.py` to migration support: https://github.com/pi-top/pi-top-Python-SDK-Migration-Support/commit/59b1e487cfe3cf743d892fe59944d6ddc141e28c
Added LGTM comment format to false positive 'unused imports'.
Still to fix: 2 instances of  `Modification of parameter with default` in `recreatable.py`.
=> LGTM fixes

.github/workflows/create-draft-release-on-chglog-merge.yml
So that it can be drop-in replaced elsewhere!
=> Generalise build workflow

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/suggestion.md, docs/more/contributing.rst
=> Drop references to deprecated GitHub wiki

examples/recipes/camera_drowsiness_buzzer.py, pitop/processing/algorithms/faces/core/face.py, pitop/processing/algorithms/faces/core/face_utils.py, pitop/processing/algorithms/faces/face_detector.py, pitop/processing/core/vision_functions.py, tests/test_face_and_emotion_detector.py
- Remove setting face angle within Face Detector and instead calculate it upon user requesting it from Face class
- Added various convenience properties to Face class for doing fun things in Further challenges with all the face data we have available:
- `left_eye_center` and `right_eye_center`
- `pupil_distance `
- `left_eye_dimensions `and `right_eye_dimensions` - detecting drowsiness
- `mouth_dimensions `- play sounds or control servos when the mouth is open, or do a rudimentary emotion detector
- `nose_bottom` - overlaying e.g. a moustache image below the nose
- Rename `center_top_left_zero` to `center_default` and add docstrings to explain it better. Still not happy with this name though
TODO: 
- ~~finish Further challenge and ensure everything desired is in this PR before merging~~
- …
=> Face updates

pitop/miniscreen/oled/assistant.py, pitop/miniscreen/oled/oled.py
=> Move rendering from miniscreen to assistant

pitop/keyboard/vendor/pynput/__init__.py, pitop/keyboard/vendor/pynput/_logger.py, pitop/keyboard/vendor/pynput/keyboard/_base.py, pitop/keyboard/vendor/pynput/keyboard/_darwin.py, pitop/keyboard/vendor/pynput/keyboard/_win32.py, pitop/keyboard/vendor/pynput/keyboard/_xorg.py, pitop/keyboard/vendor/pynput/mouse/_base.py, pitop/keyboard/vendor/pynput/mouse/_darwin.py, pitop/keyboard/vendor/pynput/mouse/_win32.py, pitop/keyboard/vendor/pynput/mouse/_xorg.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1263) |
Update references to the package `pyinput` which is now vendored.
n/a
-
- Install the PR artifacts
- Run the SDK example code for KeyboardButtons: https://pi-top-pi-top-python-sdk.readthedocs-hosted.com/en/stable/api_system_devices.html#keyboard-button
-
=> Fix pyinput references

pitop/common/sys_info.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1275) |
- Add network interfaces enum to `pitop.common.sys_info``
- Add function to get pi-top IP address
-
-
-
=> Add helper to get pi-top IP address

pitop/common/switch_user.py
- Adds helpers for running process as another user, taken from further-link. This is intended to be shared between further-link and the miniscreen's new [project menu](https://github.com/pi-top/pi-top-4-Miniscreen/pull/283/files).
- I've tested manually but it could do with a test suite.
-
-
=> Add switch_user common helpers

examples/pulse/leds-fancy_demo.py, examples/pulse/leds-pong_demo.py, examples/recipes/encoder_motor_rover.py, examples/virtual_hardware/led_simulate.py, examples/virtual_hardware/pitop_simulate.py, pitop/miniscreen/oled/oled.py, pitop/virtual_hardware/__init__.py, pitop/virtual_hardware/mock_hardware/vendor/Mock/GPIO.py, tests/test_bitwise_ops.py
=> fix: ignore intentional precommit linter errors

packages/common/pitop/common/switch_user.py
=> Readd switch_user helpers

debian/control, packages/display/README.rst, packages/keyboard/README.rst, packages/pitop/setup.py, packages/pma/README.rst, packages/processing/README.rst, packages/robotics/README.rst, packages/system/README.rst
=> Fix subpackage bits

debian/control, packages/pitop/setup.py
=> Add 'virtual_hardware' as dependency for 'pitop' package

README.rst, dev-install.sh, packages/pitop/README.rst
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1373) |
Update README with development installation instructions
-
-
-
=> Update README with development installation instructions

debian/rules, docs/conf.py
The online docs for this branch can be found [here](https://pi-top-pi-top-python-sdk.readthedocs-hosted.com/en/fix-docs/api_pma_components.html#button)
-
-
-
=> Fix docs building for readthedocs

packages/common/pitop/common/ptdm.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1273) |
- Add power button press/release messages to ptdm
-
-
-
=> Add power button messages to ptdm

.github/workflows/deploy-python-release-on-publish.yml
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1374) |
- Use `pypa/gh-action-pypi-publish` to release build to PyPI; skip errors if a version was already uploaded.
- Upload dist artifacts to workflow.
-
-
-
=> Deploy to PyPI using GitHub action

packages/pma/pitop/pma/encoder_motor.py
=> Fix EncoderMotor class recreating from file

packages/cli/pitopcli/support_core/ptsoftware.py
=> Support CLI handles systemd template units

packages/camera/setup.py, packages/common/setup.py, packages/core/setup.py, packages/pitop/setup.py, packages/processing/setup.py, tests/requirements.txt
=> Don't use python_version in package dependencies

packages/common/pitop/common/flask_sockets.py, packages/common/setup.py
=> Add gevent-websocket dependency

.github/workflows/test-all-commits.yml, tests/requirements.txt
=> Run simulation tests in a separate step

packages/pitop/pitop/labs/web/blueprints/controller/__init__.py, packages/pitop/pitop/labs/web/blueprints/rover/__init__.py, packages/pitop/pitop/labs/web/utils.py
=> Make labs web blueprints compatible with Flask 2.0

.readthedocs.yaml, docs/requirements.txt
=> Fix documentation builds in readthedocs

packages/common/pitop/common/sys_info.py
=> Reduce logging level when getting device IP address

packages/camera/pitop/camera/core/cameras/usb_camera.py
=> Create camera using all indexes if auto detection fails

packages/robotics/pitop/robotics/drive_controller.py, tests/test_drive_controller.py
- Add `distance` argument to most of `DriveController` methods to increase control over the robot.
- Re-work `rotate` function to improve robot rotation accuracy; by default it will rotate considering the new argument `max_speed_factor`, which is by default set to 30% of the max angular speed.
-
-
-
=> Add distance argument to DriveController methods

conftest.py, examples/labs/image_processing_explorer/index.html, examples/labs/image_processing_explorer/main.py, examples/labs/image_processing_explorer/run.py, packages/processing/pitop/processing/algorithms/ball_detect.py, packages/processing/pitop/processing/algorithms/hsv_color_ranges.py, packages/processing/pitop/processing/algorithms/line_detect.py, packages/processing/pitop/processing/core/vision_functions.py, tests/test_ball_detector.py, tests/test_line_detector.py
=> Line & ball detector support setting a custom color

packages/common/pitop/common/current_session_info.py
=> Sort display list to determine user using display

docs/api_robotics.rst, docs/index.rst, examples/recipes/drive_controller.py, packages/robotics/pitop/robotics/pan_tilt_controller.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/SWE-344) |
- Add robotics section to docs with DriveController, PanTiltController & PincerController docs
-
-
-
=> Add robotics section to docs

packages/robotics/pitop/robotics/drive_controller.py
- Fix: add sleep after setting synchronous mode and starting synchronous movement to allow hub to process the new values for the registers. 
-
-
-
=> Drive controller set unset sync movement
