pi-top/pi-top-Python-SDK

- cli/pt_battery.py
`Argparser` has issues managing the `%` character in the helper strings (See [1](https://github.com/PyTorchLightning/pytorch-lightning/pull/499), [2](https://stackoverflow.com/questions/21168120/python-argparse-errors-with-in-help-string))
This caused an error when `Argparser` tries to display the `pt-battery` command parameters (by using an unknown parameter or just doing `pt-battery -h`):
```
pi@pi-top:~ $ pt-battery -h
Error getting battery info: unsupported format character ')' (0x29) at index 34
```
The solution is to escape the character properly, fixing `pt-battery -h`:
```
pi@pi-top:~ $ pt-battery -h
usage: pt-battery [-h] [-s] [-c] [-t] [-w] [-v]
Get battery information from a pi-top.
optional arguments:
-h, --help            show this help message and exit
-s, --charging-state …
```
> pt_battery: display help properly

- pitop/oled/__init__.py
`OLEDImage` is required in some of the examples.
> Import OLEDImage in pitop.oled

- .github/workflows/test.yml
Add pytest job to test workflow
Some quirks we should be able to remove in furture:
- Installs pitopcommon from source as it is not yet published to PyPi
- Uses Python Version 3.7 (same as pi-topOS) because PyV4L2Camera errors on 3.9 (the default).
> Add pytest job to test workflow

- pitop/pma/common/encoder_motor_registers.py
- pitop/pma/encoder_motor_controller.py
Motor labels are M0 to M3, not M1 to M4
Given example code uses M3 so this change still compatible with that
> Update motor control registers to match expansion plate labels

- pitop/miniscreen/oled/core/canvas.py
- pitop/miniscreen/oled/core/image_helper.py
- pitop/miniscreen/oled/oled.py
- pitopcli/oled.py
Images (including animated ones) can now be sent without any pre-processing for the OLED from a file path, URL or PIL image and should render correctly.
CLI now uses API for animation directly.
Animations respect GIF frame lengths.
> Improve OLED animation handling

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/suggestion.md
Part of https://github.com/pi-top/pi-top-Python-SDK/issues/42
I picked this up because I started writing a bug report, and actually I resolved my issue in the process of looking up the system info etc, so the process works well, but I thought would still improve it a bit based on that experience.
Both:
- brief explanation of how to fill out the template
- template answers to replace are written in italics to more easily differentiate those from parts that were completed 
- takes out some of the overly formal/patronizing language some people were concerned about
Bug template:
- provide a few more suggestions & prompts for info (eg output logs, photos, additional context)
- only link to the system information page once where it's relevant
- suggest drag & drop of the pt-diagnostics file …
> Improve issue templates

- .github/ISSUE_TEMPLATE/config.yml
closes #66 
The language targets beginner programmers since those are the people we want to push from Github to Further.
> Add Further to issue template contact links

- pitopcli/cli_base.py
- pitopcli/display.py
- pitopcli/oled.py
- pitopcli/pitop.py
- Remove deprecated CLI subcommands from `pi-top`
- Print usage help message if CLI subcommands are not provided
```
(venv) pi@pi-top:~/pi-top-Python-API $ pt
usage: pi-top [-h] {battery,devices,display,oled} ...
optional arguments:
-h, --help            show this help message and exit
Subcommands:
Set of valid subcommands to use to interface with your pi-top
{battery,devices,display,oled}
valid subcommands
battery             Get battery information from a pi-top
devices             Get information about device and attached pi-top
hardware
display             communicate and control the device's display
oled                pi-top OLED quick text
```
```
(venv) pi@pi-top:~/pi-top-Python-API $ pt display
usage: pi-top display [-h] {brightness,backlight,blank_time} ...
optional arguments: …
```
> Improve CLI messages on missing arguments

- debian/changelog
- pitop/system/peripherals.py
On `system.peripherals`:
- Fix legacy peripherals detection.
- Refactor detection of upgradable peripherals.
- Add docstrings to functions.
> Fix legacy peripheral detection

- debian/changelog
- pitop/miniscreen/buttons/buttons.py
- pitop/miniscreen/oled/core/device_controller.py
Buttons can now only be used by a single process, and use a globally recognised buttons lock file, similar to how the OLED works. `Buttons.is_active` can be used by sys oled to determine if it is active with the user.
> Rework miniscreen lock files

- debian/changelog
- pitop/pma/ultrasonic_sensor.py
Increase timeout for echo pin from 100ms to 200ms. @jcapona says that this is allowing him to get higher distances, whereas I am not getting above ~60cm.
Gpiozero warnings are now debug prints.
We hide `RuntimeError: could not find io module state (interpreter shutdown?)` errors from native factory, until we have found a way to effectively manage this. The best solution would be to go from native factory back to RPi.GPIO, but this is not working well with luma, the OLED's internal library, as this leads to the "mixing libraries" issue described here: https://github.com/gpiozero/gpiozero/issues/783
If we don't get a response back from the echo pin, then we assume that distance is max.
> Patch Ultrasonic Sensor

- README.rst
- debian/changelog
- docs/index.rst
- pitop/miniscreen/oled/oled.py
Also ensure that text can be displayed with `str()`
> Fix text wrapping when displaying multiline text in OLED

- pitop/miniscreen/buttons/buttons.py
- pitop/miniscreen/miniscreen.py
- pitop/miniscreen/oled/core/device_controller.py
- pitop/miniscreen/oled/oled.py
- pitopcli/oled.py
This simplifies what is exposed to the user. `pt-sys-oled` will use an environment variable to get its desired behaviour.
> Use environment variable for miniscreen non-'exclusive mode'

- .github/workflows/build-arm-on-commits-to-master.yml
- .github/workflows/tag-and-draft-release-on-changelog-pr-merge.yml
- debian/control
- debian/source/lintian-overrides
Package does not contain anything arch-dependent. Therefore, defining the package as "Architecture: all" allows us to compile the packages natively on `amd64` (speeding up builds by ~10x!), and produce binary packages that can be used anywhere.
> Use "Architecture: all"

- .github/workflows/tag-and-draft-release-on-changelog-pr-merge.yml
Secrets and environment variables can't be used for job-level conditionals. Therefore, we create a pre-requisite job with an exposed output variable that _can_ be used.
> Fix release pipeline

- debian/control
- pitop/camera/camera.py
- pitop/camera/core/cameras/usb_camera.py
- pitop/robotics/json/alex.json
Closes https://github.com/pi-top/pi-top-Python-SDK/issues/268
- If no specific camera device index is provided, loop over available devices trying to create a camera object.
- The index is no longer stored in the camera state, unless it's explicitly set by the user.
> Loop over available devices to create camera object

- examples/pma/servo_motor.py
- pitop/pma/servo_motor.py
Closes https://github.com/pi-top/pi-top-Python-SDK/issues/269
`ServoMotor` class: keep track of `angle` and `speed` as separate properties, not through the `setting` (former `state`) property
Before releasing, we'll need to check the Further content against these changes.
> ServoMotor: don't use setting on angle/speed properties

- debian/py3dist-overrides
- docs/conf.py
- pitop/miniscreen/oled/core/device_controller.py
- pitop/protoplus/sensors.py
- setup.py
- tests/test_miniscreen_buttons.py
- tests/test_miniscreen_oled.py
Proto+ now uses `gpiozero`'s `DistanceSensor`.
RPi.GPIO is still used to suppress warnings in Luma, but with handling of failed import, this becomes a soft dependency.
Closes #266
> Drop RPi.GPIO dependency

- pitop/miniscreen/oled/oled.py
Closes #127
Also improves accuracy of FPS regulator by stopping it closer to the display function
> Stop previously running background thread when displaying anything

- .github/workflows/test-and-build-on-all-commits.yml
- .pre-commit-config.yaml
- docs/cli_tools.rst
With this PR, we will have all of the repo-specific checks handled at the `pre-commit` level.
Test coverage report now waits for pre-commit checks. Builds still wait on test coverage reports.
`--ignore-roles class --ignore-directives autoclass,automodule` seems to be needed to prevent this from showing:
```
docs/api_system_devices.rst:25: (ERROR/3) Unknown interpreted text role "class".
docs/api_pitop_device.rst:29: (ERROR/3) Unknown directive type "autoclass".
docs/api_pitop_peripheral_devices.rst:22: (ERROR/3) Unknown directive type "autoclass".
docs/api_pma_components.rst:29: (ERROR/3) Unknown directive type "autoclass".
```
However, it might be better to understand why this is happening and, preferably, address it directly.
Actual code changes are required for `rstcheck` to pass.
> Use pre-commit for RST format check

- .github/workflows/test-and-build-on-all-commits.yml
Repo is now registered with https://pre-commit.ci/, so we can drop `pre-commit` checks.
> Migrate to pre-commit.ci

- examples/camera/camera_coloured_ball_detect.py
- pitop/processing/algorithms/ball_detect.py
- tests/test_ball_detector.py
- Replace `.detect()` function in BallDetector with `__call__`
`ball_detector.detect` is long and unnecessary, just calling the ball_detector directly is more in line with how other libraries work
`detected_balls = ball_detector.detect(frame, color=["red", "green", "blue"])`
becomes:
`detected_balls = ball_detector(frame, color=["red", "green", "blue"])`
> Change .detect to direct call of class instance

- pitop/robotics/drive_controller.py
`DriveController.rotate()` only allowed the robot to rotate in one direction, ignoring the sign of the `angle` argument.
> Fix DriveController's rotate function

- docs/conf.py
- pitop/processing/core/vision_functions.py
When OpenCV is installed via pip:
```
Exception in thread Thread-6:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/pi/pi-top-Python-SDK/pitop/camera/camera.py", line 255, in __process_camera_output
self.on_frame(self.__get_processed_current_frame())
File "/home/pi/further/608ab650d0b357001b0f3945/line_follow.py", line 14, in drive_based_on_frame
processed_frame = process_frame_for_line(frame)
File "/home/pi/pi-top-Python-SDK/pitop/processing/algorithms/line_detect.py", line 40, in process_frame_for_line
line_contour = find_largest_contour(image_mask)
File …
```
> Use imutils to ensure contour is grabbed regardless of cv version

- pitop/pma/button.py
- pitop/pma/buzzer.py
- pitop/pma/led.py
- pitop/pma/ultrasonic_sensor.py
Using the NativeFactory (as opposed to RPi.GPIO factory) in GPIOZero causes issues with cleanup of components:
```
pi@pi-top:~ $ python3 -c "from pitop import Button;Button('D1')" # instantiate a button to trigger the problem
pi@pi-top:~ $ python3 -c "from pitop import LED;l = LED('D1')" # with variable to produce error
Exception ignored in: <function GPIOBase.__del__ at 0xb5781738>
Traceback (most recent call last):
File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 151, in __del__
File "/home/pi/pi-top-Python-SDK/pitop/pma/led.py", line 72, in close
File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 225, in close
File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 110, in close
File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line …
```
> Change all PMA components to use RPi.GPIO pin factory

- examples/recipes/robot_head_rotation_tracker.py
- pitop/robotics/tilt_roll_head_controller.py
`tilt_roll` -> `head` 
`tilt_servo` -> `tilt` 
`roll_servo` -> `roll`
`robot.head.tilt` more intuitive than `robot.tilt_roll.tilt_servo`
> Make tilt roll head controller name and attributes less verbose

- pitop/miniscreen/oled/oled.py
Miniscreen's `play_animated_image` method errors if parameter `background=True`:
```
>>> miniscreen.play_animated_image_file("/usr/lib/python3/dist-packages/pitop/miniscreen/images/rocket.gif", background=True)
>>> Exception in thread Thread-9:
Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/oled.py", line 597, in __auto_play
self.display_image(frame)
File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/oled.py", line 284, in display_image
invert=invert,
File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/oled.py", line 402, in __display …
```
> Only main thread can join miniscreen background thread

- pitop/miniscreen/oled/oled.py
My use case is to display emojis for a memory game.
It's unfortunate that Pillow ImageFont does [not support](https://github.com/python-pillow/Pillow/issues/4808) combining fonts, so that fallback fonts could be automatically used for characters not in the default. One possibility would be for us to [create](https://stackoverflow.com/a/35636648) and use font with the combinations manually. This `font` option would allow a user to do so themselves at least.
> Add keyword arg to select font to miniscreen display text methods

- debian/py3dist-overrides
- setup.py
Closes #383
`setup.py` defines Python dependency versions. Uses [`dh_python3`](https://www.systutorials.com/docs/linux/man/1-dh_python3/) to set Debian package version from this version.
Confirmed to install on Buster.
Missing version strings:
```
python3-monotonic
python3-sklearn
python3-pil
python3-serial
python3-numpy
```
> Add dependency versions

- debian/py3dist-overrides
- docs/conf.py
- pitop/camera/core/cameras/usb_camera.py
- pitop/core/ImageFunctions.py
- pitop/core/import_opencv.py
- pitop/processing/core/vision_functions.py
- setup.py
- tests/test_ball_detector.py
- tests/test_face_and_emotion_detector.py
This appears to work just as well on buster with all the examples, I am yet to test bullseye.
I found that a warning would be printed when creating a cv2.VideoCapture with an invalid device as part of the scan in  `list_device_indexes` - `Unable to stop the stream: Invalid argument`. I wasn't able to silence these but found that we can avoid doing this scan ourselves by passing index -1 to VideoCapture, which makes it find the first working device itself (works even when this is not video0).
Also I moved import_opencv helper into pitop.core so it could be shared between the processing module, ImageFunctions, and now UsbCamera.
> OS-1102 Replace UsbCamera PyV4L2Camera dependency with cv2.VideoCapture

- examples/pma/buzzer.py
- pitop/pma/button.py
- pitop/pma/buzzer.py
- pitop/pma/led.py
- pitop/pma/ultrasonic_sensor.py
- pitop/protoplus/sensors.py
As it currently stands any code using a digital output such as a buzzer, will not work properly when connected to port D4. This is caused by the miniscreen using the same pin as port D4 (SPI 1 clash - [related issue here](https://github.com/pi-top/pi-top-Python-SDK/issues/337)). 
Unfortunately we have a lot of examples that suggest using D4 as the default port, so a lot of users will immediately run into this problem. I've changed every example port to D0 instead of D4. The underlying issue of D4 not working properly will be address in a future fix.
> Changed all D4 examples to D0

- debian/py3dist-overrides
This is part of the `-full` package with the dependency explicitly provided, so shouldn't have a dist override.
> Drop onnxruntime as core dependency

- examples/system/pitop_load_configuration.py
- examples/system/pitop_overview.py
- pitop/miniscreen/oled/assistant.py
- pitop/miniscreen/oled/oled.py
- Miniscreen's `get_recommended_text_pos` now returns a value (previously was a reference to a function).
- When drawing multiline text, `font` & `font_size` are considered in order to break input string correctly.
Also:
- Updates references to deprecated functions in example.
- Reference buttons through `Pitop.miniscreen` in example.
> [buster] Fix miniscreen issues

- examples/system/pitop_load_configuration.py
- examples/system/pitop_overview.py
- pitop/miniscreen/oled/assistant.py
- pitop/miniscreen/oled/oled.py
- Miniscreen's `get_recommended_text_pos` now returns a value (previously was a reference to a function).
- When drawing multiline text, `font` & `font_size` are considered in order to break input string correctly.
Also:
- Updates references to deprecated functions in example.
- Reference buttons through `Pitop.miniscreen` in example.
> Fix miniscreen issues

- pitop/miniscreen/oled/assistant.py
Fixes issue when trying to use miniscreen "display text" functions using `font_size < 12`:
```
Traceback (most recent call last):
File "test.py", line 60, in <module>
say(descriptions.get(location, f'{location}... Which way to go?'))
File "test.py", line 34, in say
screen.display_multiline_text(text, font_size=10)
File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/oled.py", line 367, in display_multiline_text
text = format_multiline_text(text, font, font_size)
File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/oled.py", line 336, in format_multiline_text
space_width, _ = get_text_size(" ")
File "/usr/lib/python3/dist-packages/pitop/miniscreen/oled/oled.py", line 331, in get_text_size
font=ImageFont.truetype(font, size=font_size),
File …
```
> Fix path to default font in oled assistant

- pitop/miniscreen/oled/core/__init__.py
- pitop/miniscreen/oled/core/lock.py
- pitop/miniscreen/oled/oled.py
This is an improvement in decoupling the miniscreen components and giving things better names.
In addition, the lock-related methods are now more appropriately named.
Before:
```
miniscreen._when_user_starts_using_oled
miniscreen._when_user_stops_using_oled
```
Now:
```
miniscreen.when_user_controlled
miniscreen.when_system_controlled
```
Deprecated functions are provided to ensure that Buster will continue to work.
> Miniscreen: move lockfile management to another file

- debian/py3dist-overrides
- setup.cfg
It seems the python package doesn't install... and never has since #443?!
opencv is not found: https://pypi.org/simple/opencv/
it's opencv-python:  https://pypi.org/simple/opencv-python/
> Correct name of opencv-python in setup.cfg and py3dist-overrides

- pitop/robotics/navigation/core/driving_manager.py
- pitop/robotics/navigation/core/measurement_scheduler.py
- pitop/robotics/navigation/core/utils.py
- pitop/robotics/navigation/navigation_controller.py
- pitop/robotics/navigation/navigator.py
- tests/test_drive_controller.py
- tests/test_navigation_controller.py
- Decouple the calculation of `linear_speed` and `angular_speed` from `NavigationController` into the `Navigator` class. These parameters are now provided in the form of a generator, and it's used by the `NavigationController` in its `__navigate` method to perform movements using `robot_move`.
- Decouple the measurement scheduler from `NavigationController` into `MeasurementScheduler`.
> Navigation controller refactor

- pitop/common/sys_info.py
The `get_address_for_connected_device` function is used to determine the IP address of devices connected to the pi-top using the display-port cable. The pi-top leases IP addresses to devices connected in that port, so the check is basically performed by reviewing the leased IPs and pinging them to check if the client is still connected.
Since the addition of AP mode, the pi-top now assign IPs in 2 different networks: `192.168.64.0/24` for the USB port and `192.168.90.0/24` for AP. This means that as it is right now, the `get_address_for_connected_device` function returns IPs for all connected devices, which is something we might still want, but unexpected responses might result if this function was used on applications that assume that the only connection method to the pi-top is through …
> Filter devices connected to a pi-top by network

- pitop/common/command_runner.py
Set the `LANG` environment variable to `en_US.UTF-8` to print out the output of the command being run in english.
> Set output of command runner to english

- pitop/common/command_runner.py
Set the `LANG` environment variable to `en_US.UTF-8` to print out the output of the command being run in english.
> [buster] Set output of command runner to english

- debian/py3dist-overrides
- setup.cfg
Used by the CLI. Unable to run `pi-top` command on Raspberry Pi OS Lite with `pi-topd` installed without recommended dependencies.
```
from distutils.util import strtobool
```
produces
```
ModuleNotFoundError: No module named 'distutils.util'
```
> Add missing `distutils` dependency

- pitop/pma/encoder_motor.py
- pitop/pma/encoder_motor_controller.py
| Ready| [Ticket](https://pi-top.atlassian.net/browse/SWE-10) |
Error message when setting `EncoderMotor` RPMs to a value higher than maximum was confusing, since the error mentioned a maximum RPM of 6000. This is because the error is talking about the about the output of the DC motor (before the reduction gears) and not the encoder motor / wheel output.
This PR implements changes that will improve the error message by displaying the actual maximum/minimum values that the class can handle as target RPM (~114 instead of ~6000).
N/A
-
- Install artifacts in your pi-top[4].
- Connect the pi-top[4] to an Expansion Plate.
- Instantiate a `EncoderMotor` object and try to set the target RPM with a value higher than 114, which is the maximum:
```
>>> …
```
> Improve EncoderMotor class error messages

- .github/workflows/test-all-commits.yml
- conftest.py
- tests/requirements.txt
- tests/test_ball_detector.py
- tests/test_bitwise_ops.py
- tests/test_drive_controller.py
- tests/test_face_and_emotion_detector.py
- tests/test_firmware_device.py
- tests/test_i2c_device.py
- tests/test_lock.py
- tests/test_miniscreen_oled.py
- tests/test_navigation_controller.py
- tests/test_pma_encoder_motor.py
- tests/test_pma_encoder_motor_controller.py
- tests/test_pma_servo_controller.py
- tests/test_pma_ultrasonic.py
Closes #414
Re-enable test runs in CI using `pytest`.
Test run takes ~10 mins since it needs to build `dlib`. We could look for ways to improve this in the future (using a custom image with the dependency pre-installed or caching the dependency somehow).
> Re-enable test CI runs

- debian/py3dist-overrides
- pitopcli/support_core/health_check.py
- setup.cfg
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1263) |
Package `distutils` isn't pip-installable, causing issues when trying to install the SDK in editable mode. 
Since `distutils` is only used to convert a string to a boolean, it's easy to replace with basic operations. My guess is that it was used for more complex command parsing but now it's only parsing the output of `raspi-config nonint` commands, which only outputs 0 or 1.
N/A
-
-
-
> Remove 'distutils' dependency

- .github/workflows/deb-release.yml
- .github/workflows/deploy-python-release-on-publish.yml
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/SWE-43) |
Use PAT instead of the default Github Token when creating a release. This allows the action to trigger other actions, as documented in https://docs.github.com/en/actions/security-guides/automatic-token-authentication
-
-
-
> Use PAT when creating a Github release

- .github/workflows/deb-release.yml
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1302) |
Github releases are now automatically triggered when the 'bump-changelog' pull request is merged. The workflow can still be triggered manually via the 'Actions' tab.
-
-
-
> Automatically create release on changelog PR merge

- pitop/miniscreen/oled/core/lock.py
| Ready | [Ticket](https://pi-top.atlassian.net/browse/OS-1331) |
- Reverts part of 84be118 from #536.
The daemonize option os._exits the thread,
causing applications using it (eg pt-miniscreen) to suddenly exit. We
don't need to use the daemonize option since we are already running
Notifier.loop in a daemon thread.
https://github.com/seb-m/pyinotify/blob/0f3f8950d12e4a6534320153eed1a90a778da4ae/python3/pyinotify.py#L1316-L1317
- If you use the current SDK master when running pt-miniscreen, it will suddenly exit on the first run. Subsequent runs succeed only because the daemonize option errors out before exiting due to the lockfile already existing.
> fix: sudden exit caused by pyinotify.Notifier.loop daemonize option

- pitop/camera/core/cameras/usb_camera.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1173) |
Closes  #495 
Specify the `V4L2` backend for the USB camera capture object, which tells the video capture object that the cameras support capturing via `libv4l`. The default value `CAP_ANY` would probe the device to determine the correct backend to use, one of them being `CAP_GSTREAMER`, which prints the warning messages when unable to initialize.
The list of available backends can be found [here](https://docs.opencv.org/4.x/d4/d15/group__videoio__flags__base.html#ga023786be1ee68a9105bf2e48c700294d). Also, [this](https://docs.opencv.org/4.x/d0/da7/videoio_overview.html) is an interesting read. 
-
-
-
> Specify camera backend on cv.VideoCapture

- debian/control
- pitop/pma/imu_controller.py
- pitop/system/device.py
- pitopcli/imu.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1322) |
- Raise an Exception when trying to use the IMU on latest Expansion Plate.
- Replace usage of `pt-i2cdetect` (now deprecated) with `i2cping`.
-
-
-
> Detect and raise exception when IMU is used with new Expansion Plate

- debian/py3dist-overrides
- packages/pitop/setup.py
| Ready | no Ticket |
- pip install pitop was failing for me due to a dependency on 'pitop.cli' when the package is published as 'pitopcli'
- also update the name in the debian dist overrides
-
-
-
> Fix name of pitopcli package

- packages/common/pitop/common/ptdm.py
- packages/miniscreen/pitop/miniscreen/oled/oled.py
- tests/test_oled.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1379) |
Add new `PUB_PITOPD_READY` message to be handled by `pi-topd` when it's initialized.
-
-
-
> Reset miniscreen after pi-topd is initialized

- packages/common/pitop/common/pt_os.py
Update detection of `pi` user default password; since pi-topOS is now built on top of the latest Raspberry Pi image, we manually set the username and password; this PR updates the text that is looked up in `/etc/shadow` based on [this](https://github.com/pi-top/pi-topOS-Build/blob/master/playbooks/configure_pi_top_os.yml#L19)
-
-
-
> Update detection of pi user default password

- packages/common/pitop/common/sys_info.py
On first boot we continuously try to get the IP address of connected devices via USB or AP. This sometimes fails because the file with the leases doesn't exist yet. 
The changes in this PR handle that case, returning an empty string, which means that no IP lease exist at the moment.
-
-
-
> Handle errors when reading leased IPs

- packages/pitop/pitop/__init__.py
- packages/robotics/pitop/robotics/__init__.py
These exports follow the existing pattern of exporting all the key interfaces from both their subpackage and the top-level package.
In particular this aims to fix the import of DriveController from pitop.robotics used the web-portal rover controller, which assumed this would be available when switching to use subpackages.
-
-
-
-
> Add additional exports to the pitop and robotics modules

- packages/common/pitop/common/sys_info.py
`Error reading dhcpd leases: /var/lib/dhcp/dhcpd.leases file not found` log messages are polluting the journal, specially in legacy  devices that don't use of the dhcp server.
> Reduce logging when dhcp leases file doesn't exist

- packages/common/pitop/common/sys_info.py
- tests/test_sys_info.py
- Supports finding IP leases made by dnsmasq, as this is the service that provides them in bookworm. This fixes some events that were not triggering in the web portal.
-
-
-
> Find Dnsmasq IP leases

- packages/common/pitop/common/flask_sockets.py
- Get `werkzeug` version from `importlib.metadata` instead of using the `__version__` property, which was removed in the latest versions of the package. This bit of code is used in the function that decides if the vendored sockets from `flask_sockets` for `bookworm` should be patched or not.
-
-
-
> Get werkzeug version using importlib

- .github/workflows/deploy-python-release-on-publish.yml
- .pre-commit-config.yaml
- packages/battery/setup.py
- packages/camera/setup.py
- packages/cli/setup.py
- packages/common/setup.py
- packages/core/setup.py
- packages/display/setup.py
- packages/keyboard/setup.py
- packages/miniscreen/setup.py
- packages/pitop/setup.py
- packages/pma/setup.py
- packages/processing/setup.py
- packages/robotics/setup.py
- packages/simulation/setup.py
- packages/system/setup.py
- Fix publishing packages to PyPI by setting the description content type.
- 'deploy' workflow uploads packages to test.pypi when ran manually, for testing purposes.
-
-
-
> Add description content type on setup.py

- packages/pma/pitop/pma/encoder_motor.py
- tests/test_drive_controller.py
- tests/test_pma_encoder_motor.py
| Ready/Hold | [Ticket](https://pi-top.atlassian.net/browse/OS-1450) |
- Update EncoderMotor default wheel diameter to 7cm. This is the diameter of the wheel when put in a flat surface.
- Update docs accordingly.
- Update tests: some calculations changed due to the change in the default value of wheel diameter.
- Updated drive controller test to pytest style.
-
-
-
> Update EncoderMotor default wheel diameter

- packages/robotics/pitop/robotics/drive_controller.py
The DriveController enables synchronous mode in its constructor, which causes issues when trying to use an EncoderMotor individually; this PR will enable synchronous mode for each movement of the DriveController and then disable it, allowing to use an EncoderMotor alongside the DriveController.
Sample snippet:
```
from pitop import DriveController
d = DriveController()
d.forward(0.5)
d.stop()
left_motor = d.left_motor
left_motor.set_target_rpm(144)
```
-
-
> DriveController set synchronous mode on each movement
